title: Agujeros negros
author: EduardoC12
theme: minima
email: l181061197@mulege.tecnm.mx
description: > # this means to ignore newlines until "baseurl:"
  Se muestran información general acerca de los agujeros negros.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
